/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pijewski' at '30.07.15 20:10' with Gradle 2.5
 *
 * @author pijewski, @date 30.07.15 20:10
 */

package a;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Library {

	private static final Logger LOGGER = LoggerFactory.getLogger(Library.class);

    public static void main(String... args) {
    	LOGGER.info("Hello World!");
    	final Library library = new Library();
        library.foo();
    	library.foo("Abracadabra");
    	LOGGER.info("Bye, bye!");
    }

    public void foo() {
    	LOGGER.info("Inside foo()");
    }

    public void foo(String arg) {
        LOGGER.info("Inside foo({})", arg);
    }
}

